# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b417fc5b284849f756108b9d26c1b6800e4077b8e6aca237296610685f9fc22341b307cfb1bf8ce4dab7c0b32c449cc42bf39eb5346ec76e4400efaa790ee612

test:
  secret_key_base: f68cb1fef1b46bdcf2be1f7fdddb24580e9fbdea8c0559ee37e843c195fd081b7d06f6b4ff006746c44fcfb39ecf7548d5ef901452a5e2681bff9de3341073ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
