# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'zXhESCsxEZygNaMK0XcK61vfH'
  twitter_api_secret: 'U2igQZypkrpchgjeqUjnsyip1j2VR9liIseIjcpgVtH55BXagz'

development:
  secret_key_base: f80cce01897743fd967405d697b55ec70507088dfaa58712181b99f9dddd2e53b096e42eea0cefddd8a91f4aba3c507b083f370997b3d33c03fd3605f8c7305e
  <<: *default_twitter

test:
  secret_key_base: 89bbecb5d4e76e8037697b9fe7dadf6e959d5c031df126ae01c5476a4915f33273c7fc23a230060ef6791000b848af892b0a3b9b227c758755b20abd3c05f6b2
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
